import React from 'react';
import { JBCCard } from '../react/Card';
import { JBCButton, JBCIconButton } from '../react/Button';
import { JBCTooltip } from '../react/JBCTooltip';
import { JBCIcon } from '../react/Icon';

const TooltipSystem: React.FC<{ theme?: 'light' | 'dark' }> = ({ theme = 'dark' }) => {
  return (
    <div className="space-y-16">
      <JBCCard elevation="low" className="p-8">
        <h3 className="text-xl font-bold mb-4">Feedback / Tooltips</h3>
        <p className="text-sm opacity-70 leading-relaxed">
          Tooltips provide brief, contextual information that appears on hover, focus, or long-press. 
          They are essential for labeling icon-only actions and explaining complex financial 
          terminology without cluttering the primary interface.
        </p>
      </JBCCard>

      {/* Interactive Examples */}
      <div className="space-y-8">
        <h4 className="text-[10px] font-mono uppercase tracking-widest opacity-60">Interactive Examples</h4>
        <div className="flex flex-wrap items-center gap-12">
          <div className="space-y-4">
            <span className="text-[10px] font-bold opacity-40 block uppercase">Icon-Only Labeling</span>
            <div className="flex gap-4">
              <JBCTooltip content="Edit Portfolio">
                <JBCIconButton icon="ri-edit-line" variant="outlined" />
              </JBCTooltip>
              <JBCTooltip content="Delete Transaction" placement="bottom">
                <JBCIconButton icon="ri-delete-bin-line" variant="destructive" />
              </JBCTooltip>
              <JBCTooltip content="Settings" placement="right">
                <JBCIconButton icon="ri-settings-4-line" variant="ghost" />
              </JBCTooltip>
            </div>
          </div>

          <div className="space-y-4">
            <span className="text-[10px] font-bold opacity-40 block uppercase">Financial Glossary</span>
            <div className="p-4 rounded-xl border border-dashed border-black/10 dark:border-white/10 flex items-center gap-3">
              <span className="text-sm">Current Pool </span>
              <JBCTooltip content="Annual Percentage Rate. The yearly interest generated by a sum that's charged to borrowers or paid to investors." maxWidth={250}>
                <span className="text-sm font-bold text-jbc-cyan border-b border-dotted border-jbc-cyan cursor-help">APR 12.4%</span>
              </JBCTooltip>
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
        <div className="space-y-6">
          <h4 className="text-lg font-bold">Design Rules</h4>
          <div className="space-y-4 text-xs opacity-70">
            <p>Tooltips should be used sparingly to avoid "visual noise."</p>
            <ul className="space-y-4">
              <li className="flex gap-3">
                <i className="ri-checkbox-circle-line text-jbc-success mt-0.5" />
                <div>
                  <span className="font-bold block text-black dark:text-white">When to Use</span>
                  Required for icon-only buttons. Used for explaining technical abbreviations (APR, TVL, slippage).
                </div>
              </li>
              <li className="flex gap-3">
                <i className="ri-close-circle-line text-jbc-error mt-0.5" />
                <div>
                  <span className="font-bold block text-black dark:text-white">When NOT to Use</span>
                  Never put critical information inside a tooltip. Do not use for text that is already visible on screen.
                </div>
              </li>
            </ul>
          </div>
        </div>

        <div className="space-y-6">
          <h4 className="text-lg font-bold">Accessibility & Behavior</h4>
          <div className="p-6 rounded-2xl bg-black/5 dark:bg-white/5 border border-white/5 space-y-4">
            <div className="flex items-center gap-3">
              <JBCIcon name="ri-user-smile-line" size={20} className="text-jbc-cyan" />
              <span className="text-xs font-bold uppercase tracking-widest">A11Y Standards</span>
            </div>
            <ul className="text-xs opacity-60 space-y-3">
              <li>• <code className="text-jbc-cyan">aria-describedby</code>: Tooltips are programmatically linked to their trigger elements.</li>
              <li>• <code className="text-jbc-cyan">Focus Support</code>: Keyboard users see tooltips when tabbing through the UI.</li>
              <li>• <code className="text-jbc-cyan">Safe Delay</code>: A 200ms delay prevents tooltips from flashing during rapid mouse movement.</li>
              <li>• <code className="text-jbc-cyan">Mobile Support</code>: Long-pressing triggers tooltips on touch devices.</li>
            </ul>
          </div>
        </div>
      </div>

      {/* Code Usage */}
      <div className="space-y-6">
        <h4 className="text-[10px] font-mono uppercase tracking-widest opacity-60">Implementation Guide</h4>
        <div className="relative bg-[#0D1117] border border-black/10 dark:border-[#30363D] rounded-2xl p-8 group overflow-hidden">
          <pre className="font-mono text-sm leading-relaxed overflow-x-auto text-[#E6EDF3]">
            <code>
              <span className="text-[#8B949E] italic">// Wrap any interactive component</span><br/>
              &lt;JBCTooltip content=<span className="text-[#A5D6FF]">"View Details"</span> placement=<span className="text-[#A5D6FF]">"top"</span>&gt;<br/>
              &nbsp;&nbsp;&lt;JBCButton&gt;Inspect&lt;/JBCButton&gt;<br/>
              &lt;/JBCTooltip&gt;<br/><br/>
              <span className="text-[#8B949E] italic">// Rich content support</span><br/>
              &lt;JBCTooltip <br/>
              &nbsp;&nbsp;content={<span className="text-[#FF7B72]">&lt;div&gt;</span>Estimated TVL <span className="text-[#A5D6FF] font-bold">$1.2B</span><span className="text-[#FF7B72]">&lt;/div&gt;</span>}<br/>
              &nbsp;&nbsp;maxWidth={<span className="text-[#A5D6FF]">250</span>}<br/>
              &gt;<br/>
              &nbsp;&nbsp;&lt;span&gt;Liquidity Pool&lt;/span&gt;<br/>
              &lt;/JBCTooltip&gt;
            </code>
          </pre>
        </div>
      </div>
    </div>
  );
};

export default TooltipSystem;
